name: Build site and test image

on:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --destination ./public

      - name: Install zopfli
        run: sudo apt-get install -y --no-install-recommends zopfli

      - name: Compress public static files
        run: |
          cd public
          for file in $(find . -type f)
          do
              zopfli "$file"
              rm "$file"
              touch -r "$file".gz "$file"
          done

      - name: Build test image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: silentpaymentsxyz:test
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/silentpaymentsxyz:latest
          cache-to: type=inline

      - name: Test-run image
        run: |
          docker run --rm silentpaymentsxyz:test &
          PID=$!
          sleep 10
          kill -SIGINT $PID # this will return a non-zero exit code if the container dies early on
